config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'wikis#index'
  get '/welcome' => 'welcome#index'

  resources :wikis do
    resources :collaborations, only: [:create, :destroy]
  end

  resources :users, only: [:update]

  resources :charges, only: [:new, :create]
  resources :subscriptions, only: [:new, :create, :destroy]

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  validates :user, presence: true

  after_save :set_owner_as_collaborator

  # What is this method doing here?
  # That's what we have controllers for silly!
  def add_collaborator(user)
    Collaboration.create(:user_id => user.id, :wiki_id => self.id)
  end

  def collaborators
    self.collaborations.map { |c| c.user }
  end

  private

  def set_owner_as_collaborator
    user = self.user
    Collaboration.create(:user_id => user.id, :wiki_id => self.id)
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = current_user.owned_wikis.build(wiki_params)

    if @wiki.save
      redirect_to wikis_path, notice: "wiki was saved successfully."
    else
      flash[:error] = "Error creating wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.update_attributes(wiki_params)

    if @wiki.save
      redirect_to @wiki
    else
      flash[:error] = "Error saving wiki. Please try again"
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice]= "Wiki successfully removed"
      redirect_to :wikis
    else
      flash[:error] = "Sorry, there was an error in deleting the wiki please try again"
      render :index
    end

  end

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :user_id)
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.haml
.row
  .col-md-8
    = form_for wiki do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: "form-control", placeholder: "Wiki title"

      .from-group
        = f.label :body
        = f.text_area :body, class: "form-control", placeholder: "Wiki body"

      %br

      - if current_user.role == "admin" || current_user.role == "premium"
        .form-group
          = f.check_box :private, checked_value: "true", unchecked_value: "false"
          = f.label :private

      .form-group
        = f.submit "Save", class: 'btn btn-success'

app/views/wikis/edit.html.haml
%h1 Edit wiki

.row
  .col-md-8
    = render partial: 'form', locals: { wiki: @wiki }
  .col-md-4
    = render partial: 'collaborations/index', locals: { wiki: @wiki }
    %br
    = render partial: 'collaborations/create', locals: { wiki: @wiki }

app/views/wikis/index.html.haml
- if @wikis
  %table.table
    %header
      %td Wiki
      %td Author
      %td
    - @wikis.each do |wiki|
      %tr
        %td
          = link_to markdown( wiki.title ), wiki_path(wiki)
        %td
          - if current_user && wiki.user.email == current_user.email
            = "you"
          -elsif wiki.user
            = "#{wiki.user.email}"
        %td{colspan: 2}
          - if current_user
            = link_to 'edit', edit_wiki_path(wiki)
          -if current_user && policy(wiki).destroy?
            = link_to 'delete', wiki, method: :delete, data: { confirm: 'Are you sure you want to delete this topic?' }
          -else
- else
  There are no wikis yet. Be the first to create one!

- if current_user
  = link_to 'Create wiki', new_wiki_path

app/views/wikis/new.html.haml
%h1 New wiki

.row
  .col-md-8
    = render partial: 'form', locals: { wiki: @wiki }

app/views/wikis/show.html.erb
<h3>
  <%= markdown( @wiki.title ) %>
</h3>

<p>
  <%= markdown( @wiki.body ) %>
</p>