config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'wikis#index'
  get '/welcome' => 'welcome#index'

  resources :wikis do
    resources :collaborations, only: [:create, :destroy]
  end

  resources :users, only: [:update]

  resources :charges, only: [:new, :create]
  resources :subscriptions, only: [:new, :create, :destroy]

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def new
  end

  def create
    # Creates a Stripe Customer Object, for associating with the charge
    session[:return_to] ||= request.referer

    begin
      unless customer = Stripe::Customer.create(
        :email => current_user.email,
        :card  => params[:stripeToken]
      )

        flash[:error] = "There was a problem processing your request. Please try again."
        redirect_to edit_user_registration_path
        return
      end

      # Creating a stripe charge object
      unless charge = Stripe::Charge.create(
        :customer    => customer.id, # This is not the same as the user id--it's coming from that Customer object
        :amount      => 1000, # In pennies, so $10
        # TODO:  Create class and call Amount.default rather than hardcoding
        :description => "Blocipedia Premium Membership - #{current_user.email}",
        :currency    => 'usd')

        flash[:error] = "There was a problem creating the charge. Please try again"
        redirect_to edit_user_registration_path
        return
      end

    rescue Stripe::CardError => e
      redirect_to edit_user_registration_path
      flash[:error] = e.message
    end

    #if current_user.build_subscription(:customer_id => customer.id)
  #  current_user.customer_id = customer.id
    current_user.role = "premium"
    binding.pry
      current_user.save
      flash[:success] = "Thanks for the money, #{current_user.email}! Your card was charged $#{ charge.amount / 100 }.#{ charge.amount % 100 }."
      #flash[:notice] = "Successfully subscribed."
    #else
      flash[:error] = "There was a problem processing your request. Please try again."
    #end

    redirect_to root_path
  end

  def destroy
    current_user
    current_user.role = "free"
    session[:return_to] ||= request.referer

    if current_user.subscription
      subscription = current_user.subscription
    else
      raise "Error: Premium users should have subscription"
    end

    if subscription.destroy
      current_user.save
      flash[:notice] = "Successfully unsubscribed."
    else
      flash[:error] = "There was a problem processing your request. Please try again."
    end
    redirect_to root_path
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_new.html.erb
<%
  # TODO: The following data has NO buisness being in the view!
  # I'm putting it here temporarily to make the tests pass.
  # It's just data--move it out into its own class or something
%>

<%
  @stripe_btn_data = {
    :key         => "#{ Rails.configuration.stripe[:publishable_key] }",
    :description => "Blocipedia membership - #{current_user.email}",
    :amount      => 1000,
    :name => "Blocipedia",
# It might be cool to add an image as well--that will require going over the section on amazon s3 for uploading that image. This is fine for now.
    :label  => "Upgrade to Premium"
  }
%>

<%= form_tag subscriptions_path do %>

  <script
    class='stripe-button'
    src="https://checkout.stripe.com/checkout.js"
    data-key="<%= @stripe_btn_data[:key] %>"
    data-amount=<%= @stripe_btn_data[:amount] %>
    data-label=<%= @stripe_btn_data[:label] %>
    data-description="<%= @stripe_btn_data[:description] %>" >

  </script>
            <%#<%= link_to "Upgrade to Premium", subscriptions_path, method: :post, class: "btn btn-primary #{disable_class(current_user, "premium")}" %>%>
<% end %>

app/views/subscriptions/create.html.erb
<h3>Thanks!</h3>
Your card was processed successfully.

<%= "Your role is now #{current_user.role}" %>
<% if current_user.subscription %>
  <%= "Your subscription date is now #{current_user.subscription.created_at}" %>
<% end %>