config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'wikis#index'
  get '/welcome' => 'welcome#index'

  resources :wikis do
    resources :collaborations, only: [:create, :destroy]
  end

  resources :users, only: [:update]

  resources :charges, only: [:new, :create]
  resources :subscriptions, only: [:new, :create, :destroy]

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  def create
    @user = User.find(params[:collaboration][:user_id])
    @wiki = Wiki.find(params[:wiki_id])

    session[:return_to] ||= request.referer

    if Collaboration.where(:user_id => @user.id, :wiki_id => @wiki.id).empty?
      collaboration = @user.collaborations.build(:wiki_id => @wiki.id)
    else
      flash[:error] = "That user is already listed as a collaborator"
      redirect_to session.delete(:return_to)
      return
    end

    # TODO: The block above is a total kludge
    # But basically what it's trying to do is check to see if a collaboration between the given user and the id already exists
    # If it does then it won't make a new one.
    # I assume that the better way to do this would be to add a validation to the model but I haven't figured out how to do that yet.

    if collaboration.save # This doesn't work anymore because it's not a validation because we haven't really created a validation
      redirect_to session.delete(:return_to)
    else
      # Flash error message
      redirect_to session.delete(:return_to)
    end
  end

  def destroy
    @collaboration = Collaboration.find(params[:id])
    @wiki = Wiki.find(params[:wiki_id])

    if @collaboration.destroy
      flash[:notice] = "#{@collaboration.user.name} removed as collaborator"
    else
      flash[:error] = "There was a problem removing this collaborator."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def collaboration_params
    params.require(:collaboration).permit(:user_id, :wiki_id)
  end
end

app/views/collaborations/_create.html.haml
= form_for [ @wiki, Collaboration.new(:wiki_id => @wiki.id) ]  do |f|
  .form-group
    = f.label :add_collaborator, class: 'sr-only'
    = f.collection_select(:user_id, User.all, :id, :name, class: 'form-control')
  .form-group
    = f.submit "Add Collaborator", class: 'btn btn-default btn-sm'

app/views/collaborations/_index.html.haml
%h4 Collaborators:
%ul
  -#- @wiki.collaborators.each do |c|
  - @wiki.collaborations.each do |c|
    %li{:id => "user-#{c.user.id}"}
      - if c.user == current_user
        = "You"
      - else
        = c.user.name
      = link_to "X", wiki_collaboration_path(@wiki, c), method: :delete, remote: true

app/views/collaborations/destroy.js.erb
<% if @collaboration.destroyed? %>
  $('#user-' + <%= @collaboration.user.id %>).hide();
$('.main-content').prepend("<div class='alert alert-success'><%= flash[:notice] %></div>");
<% else %>
  $('#user-' + <%= @collaboration.user.id %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
<% end %>